export const ordenRecibirProveedor = [
    {
        numero_tarjeta: "2500 XXXX XXXX 5646",
        cuenta: "410010064540",
        tipo_identificacion: "C",
        identificacion: "1150214375",
        ente: "189610",
        nombre: "DANNY VASQUEZ",
        nombre_impreso: "DANNY VASQUEZ",
        tipo: "ESTÁNDAR",
        orden_pertenece: "164",
        key: 23,
        estado: "APROBADA",
        oficina_solicita: "MATRIZ",
        oficina_recepta: "EL VALLE",
        fecha_solicita: "5/1/2024 7:38:11 PM",
        estado_recepcta_proveedor: ""

    },
    {
        numero_tarjeta: "2500 XXXX XXXX 3636",
        cuenta: "410010026841",
        tipo_identificacion: "C",
        identificacion: "1105970717",
        ente: "515145",
        nombre_impreso: "ROBERTH TORRES",
        nombre: "ROBERTH TORRES",
        tipo: "BLACK",
        orden_pertenece: "164",
        key: 20,
        estado: "APROBADA",
        oficina_solicita: "MATRIZ",
        oficina_recepta: "EL VALLE",
        fecha_solicita: "5/2/2024 4:51:38 PM",
        estado_recepcta_proveedor: ""
    }
    ,
    {
        numero_tarjeta: "2500 XXXX XXXX 0101",
        cuenta: "410010061199",
        tipo_identificacion: "R",
        identificacion: "1150214375",
        ente: "515146",
        nombre_impreso: "LUIS VALDEZ",
        nombre: "LUIS VALDEZ",
        tipo: "GOLDEN",
        orden_pertenece: "164",
        key: 38,
        estado: "APROBADA",
        oficina_solicita: "MATRIZ",
        oficina_recepta: "EL VALLE",
        fecha_solicita: "5/9/2024 11:55:27 AM",
        estado_recepcta_proveedor: ""
    },
    {
        numero_tarjeta: "2500 XXXX XXXX 0214",
        cuenta: "410010094684",
        tipo_identificacion: "P",
        identificacion: "PL970713",
        ente: "515147",
        nombre_impreso: "MARIO CRUZ",
        nombre: "MARIO CRUZ",
        tipo: "ESTÁNDAR",
        orden_pertenece: "165",
        key: 48,
        estado: "APROBADA",
        oficina_solicita: "MATRIZ",
        oficina_recepta: "EL VALLE",
        fecha_solicita: "4/30/2024 4:20:30 PM",
        estado_recepcta_proveedor: ""
    },
    {
        numero_tarjeta: "2500 XXXX XXXX 1818",
        cuenta: "410010061514",
        tipo_identificacion: "R",
        identificacion: "1105970714001",
        ente: "515148",
        nombre_impreso: "NICOLE ALBAN",
        nombre: "NICOLE ALBAN",
        tipo: "BLACK",
        orden_pertenece: "165",
        key: 58,
        estado: "APROBADA",
        oficina_solicita: "MATRIZ",
        oficina_recepta: "EL VALLE",
        fecha_solicita: "5/9/2024 11:55:27 AM",
        estado_recepcta_proveedor: ""     
    }
]